version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Backend.Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./Backend:/app
      - /app/node_modules
      - ./.env:/.env
    restart: always

  frontend:
    build:
      context: .
      dockerfile: Frontend.Dockerfile
    ports:
      - "5173:80"
    depends_on:
      - backend
    restart: always